[package]
name = "ferrous-frog-app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
js-rendering = ["ferrous-frog-crawler-core/js-rendering"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
csv.workspace = true
ferrous-frog-analysis.workspace = true
ferrous-frog-crawler-core.workspace = true
ferrous-frog-export.workspace = true
ferrous-frog-extractors.workspace = true
ferrous-frog-integrations.workspace = true
ferrous-frog-parser.workspace = true
ferrous-frog-storage.workspace = true
keyring.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
semver = "1.0.28"
serde.workspace = true
serde_json.workspace = true
tauri = { workspace = true, features = [] }
tauri-plugin-notification.workspace = true
tauri-plugin-opener.workspace = true
tauri-plugin-window-state.workspace = true
tempfile.workspace = true
tokio.workspace = true
url.workspace = true

[[bin]]
name = "ferrous-frog"
path = "src/main.rs"
