[package]
name = "ferrous-frog-extractors"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
regex.workspace = true
scraper.workspace = true
serde.workspace = true
sxd-document.workspace = true
sxd-xpath.workspace = true
thiserror.workspace = true
