[package]
name = "ferrous-frog-crawler-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
js-rendering = ["dep:chromiumoxide", "dep:futures", "dep:tempfile"]

[dependencies]
anyhow.workspace = true
blake3.workspace = true
chromiumoxide = { workspace = true, optional = true }
ferrous-frog-extractors.workspace = true
ferrous-frog-parser.workspace = true
ferrous-frog-storage.workspace = true
futures = { workspace = true, optional = true }
governor.workspace = true
httpdate.workspace = true
md-5.workspace = true
psl.workspace = true
quick-xml = "0.42.0"
regex.workspace = true
reqwest.workspace = true
rustls.workspace = true
rustls-pki-types.workspace = true
rustls-platform-verifier.workspace = true
serde.workspace = true
simhash.workspace = true
tempfile = { workspace = true, optional = true }
texting_robots.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
serde_json.workspace = true
tokio = { workspace = true, features = ["test-util"] }
