[package]
name = "ferrous-frog-crawler-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
ferrous-frog-extractors.workspace = true
ferrous-frog-parser.workspace = true
ferrous-frog-storage.workspace = true
governor.workspace = true
quick-xml = "0.40.1"
regex.workspace = true
reqwest.workspace = true
serde.workspace = true
simhash.workspace = true
texting_robots.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
